export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';
export const RENDER_TEAMS_SUCCESS = 'RENDER_TEAMS_SUCCESS';
export const RENDER_MY_TEAMS_SUCCESS = 'RENDER_MY_TEAMS_SUCCESS';
export const RENDER_PERSONS_SUCCESS = 'RENDER_PERSONS_SUCCESS';
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS';
export const RENDER_ALL_PERSONS_SUCCESS = 'RENDER_ALL_PERSONS_SUCCESS';
export const TEAM_HISTORY_SUCCESS = 'TEAM_HISTORY_SUCCESS';